//
//  AddCardPresenter.swift
//  binkapp
//
//  Created by Paul Tiriteu on 22/07/2019.
//  Copyright (c) 2019 Bink. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddCardPresentationLogic
{
  func presentSomething(response: AddCard.Something.Response)
}

class AddCardPresenter: AddCardPresentationLogic
{
  weak var viewController: AddCardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AddCard.Something.Response)
  {
    let viewModel = AddCard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
