//
//  AddCardViewController.swift
//  binkapp
//
//  Created by Paul Tiriteu on 22/07/2019.
//  Copyright (c) 2019 Bink. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddCardDisplayLogic: class
{
  func displaySomething(viewModel: AddCard.Something.ViewModel)
}

class AddCardViewController: UIViewController, AddCardDisplayLogic
{
  var interactor: AddCardBusinessLogic?
  var router: (NSObjectProtocol & AddCardRoutingLogic & AddCardDataPassing)?

  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  private func setup()
  {
    let viewController = self
    let interactor = AddCardInteractor()
    let presenter = AddCardPresenter()
    let router = AddCardRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  func doSomething()
  {
    let request = AddCard.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: AddCard.Something.ViewModel)
  {
    
  }
}
