fastlane_version "1.104.0"

default_platform :ios

platform :ios do

  # Lifecycle

  before_all do |lane, options|
    # This excludes these targets from the code coverage, required if we just want BinkApp posted to Slack
    ENV["COVERAGE_EXCLUDE_TARGETS"] = ""

    # This allows the command line iTunes Connect uploaded to get through out firewall, otherwise all connections are blocked
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

  end

  after_all do |lane|
  end

  error do |lane, exception|
      notification(
        subtitle: "Fastlane: #{lane} failed",
        message: exception.message
      )
  end

  # Certificate management

  desc "Retrieve all the certificates for all targets and configures your machine to compile against devices"
  lane :setup do

    # Bink

    match(type: "appstore", app_identifier: "com.bink.wallet.neo", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.wallet.neo", readonly: true)
    match(type: "development", app_identifier: "com.bink.wallet.neo.alpha", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.wallet.neo.beta", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.wallet.neo.mr", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.wallet.neo.nightly", readonly: true)
    match(type: "adhoc", app_identifier: "com.bink.wallet.neo.gamma", readonly: true)

  end

end
