//
//  MainTabBarPresenter.swift
//  binkapp
//
//  Created by Paul Tiriteu on 22/07/2019.
//  Copyright (c) 2019 Bink. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainTabBarPresentationLogic
{
  func presentSomething(response: MainTabBar.Something.Response)
}

class MainTabBarPresenter: MainTabBarPresentationLogic
{
  weak var viewController: MainTabBarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MainTabBar.Something.Response)
  {
    let viewModel = MainTabBar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
