//
//  PaymentWalletInteractor.swift
//  binkapp
//
//  Created by Paul Tiriteu on 22/07/2019.
//  Copyright (c) 2019 Bink. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentWalletBusinessLogic
{
  func doSomething(request: PaymentWallet.Something.Request)
}

protocol PaymentWalletDataStore
{
  //var name: String { get set }
}

class PaymentWalletInteractor: PaymentWalletBusinessLogic, PaymentWalletDataStore
{
  var presenter: PaymentWalletPresentationLogic?
  var worker: PaymentWalletWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PaymentWallet.Something.Request)
  {
    worker = PaymentWalletWorker()
    worker?.doSomeWork()
    
    let response = PaymentWallet.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
