//
//  PaymentWalletPresenter.swift
//  binkapp
//
//  Created by Paul Tiriteu on 22/07/2019.
//  Copyright (c) 2019 Bink. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentWalletPresentationLogic
{
  func presentSomething(response: PaymentWallet.Something.Response)
}

class PaymentWalletPresenter: PaymentWalletPresentationLogic
{
  weak var viewController: PaymentWalletDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PaymentWallet.Something.Response)
  {
    let viewModel = PaymentWallet.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
